version: '3.9'
services:
  webapi:
    build: ./
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=IpGeoDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "5000:5000"
      - "5001:5001"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
