version: '3.9'
services:
  webapi:
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      ASPNETCORE_URLS: "https://+:5001;http://+:5000"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "YourPassword123"
    volumes:
      - ./https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"
